version: "3"

services:

  # .Net Core API Issuer
  issuer-api-dev:
    image: dts-vc-issuer-api-dev
    environment:
      APP: "dev"
      DB_CONNECTION_STRING: "Host=db;Port=${DATABASE_PORT};Database=${ISSUER_DATABASE_NAME};Username=${DATABASE_USER};Password=${DATABASE_PASSWORD};"
      ISSUER_AGENT_ADMIN_API_KEY: ${AGENT_ADMIN_API_KEY}
      ISSUER_AGENT_ADMIN_API_URL: ${ISSUER_AGENT_ADMIN_URL}
    ports:
      - ${ISSUER_API_PORT}:5000
    networks:
      - dts-vc-issuer
    volumes:
      - ../issuer-api/:/app
      - issuer-api-dev-bin:/app/bin
      - issuer-api-dev-obj:/app/obj
    depends_on:
      - db
    entrypoint: /bin/bash 
    command: [
      "-c",
      "echo waiting for db ...;
      sleep 15;
      echo \"Running database migrations...\";
      dotnet ef database update;
      echo \"Starting service...\";
      dotnet watch run --urls=http://+:5000"
    ]

  # PostgreSQL database used by the API
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: default
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - dts-vc-issuer
    volumes:
      - api-db-data:/var/lib/postgresql/data

  # Agent
  agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0
    environment:
      ACAPY_LABEL: ${AGENT_NAME}
      ACAPY_ENDPOINT: ${AGENT_ENDPOINT}
      ACAPY_GENESIS_URL: ${LEDGER_URL}/genesis
      ACAPY_WALLET_NAME: ${AGENT_WALLET_NAME}
      ACAPY_WALLET_TYPE: "indy"
      ACAPY_WALLET_KEY: ${AGENT_WALLET_ENCRYPTION_KEY}
      ACAPY_WALLET_SEED: ${AGENT_WALLET_SEED}
      ACAPY_WALLET_STORAGE_TYPE: ${AGENT_WALLET_STORAGE_TYPE}
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_WEBHOOK_URL: ${AGENT_WEBHOOK_URL}
      ACAPY_LOG_LEVEL: ${AGENT_LOG_LEVEL}
      ACAPY_AUTO_ACCEPT_INVITES: "true"
      ACAPY_AUTO_ACCEPT_REQUESTS: "true"
      ACAPY_AUTO_PING_CONNECTION: "true"
      ACAPY_AUTO_RESPOND_MESSAGES: "true"
      ACAPY_TAILS_SERVER_BASE_URL: ${TAILS_SERVER_URL}
      AGENT_HTTP_IN_PORT: ${AGENT_HTTP_IN_PORT}
      AGENT_WS_IN_PORT: ${AGENT_WS_IN_PORT}
      AGENT_ADMIN_PORT: ${AGENT_ADMIN_PORT}
      WALLET_HOST: ${WALLET_HOST}
      WALLET_PORT: ${WALLET_PORT}
      WALLET_USER: ${WALLET_USER}
      WALLET_PASSWORD: ${WALLET_PASSWORD}
    networks:
      - dts-vc-issuer
    ports:
      - ${AGENT_HTTP_IN_PORT}:${AGENT_HTTP_IN_PORT}
      - ${AGENT_WS_IN_PORT}:${AGENT_WS_IN_PORT}
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
    depends_on:
      - wallet
    entrypoint: /bin/bash
    command: [
        "-c",
        "curl -d '{\"seed\":\"${AGENT_WALLET_SEED}\", \"role\":\"ENDORSER\", \"alias\":\"${AGENT_WALLET_NAME}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 5; \
        aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_IN_PORT} \
        --inbound-transport ws '0.0.0.0' ${AGENT_WS_IN_PORT} \
        --outbound-transport ws \
        --outbound-transport http \
        --wallet-storage-config '{\"url\":\"${WALLET_HOST}:${WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${WALLET_USER}\",\"password\":\"${WALLET_PASSWORD}\",\"admin_account\":\"${WALLET_USER}\",\"admin_password\":\"${WALLET_PASSWORD}\"}' \
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${AGENT_ADMIN_MODE}",
      ]

  # Wallet
  wallet:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${WALLET_USER}
      POSTGRES_PASSWORD: ${WALLET_PASSWORD}
    networks:
      - dts-vc-issuer
    ports:
      - ${EXPOSED_WALLET_PORT}:${WALLET_PORT}
    volumes:
      - wallet-data:/var/lib/postgresql/data

networks:
  dts-vc-issuer:

volumes:
  keycloak-db-data:
  wallet-data:
  api-db-data:
  tails-storage:
  issuer-api-dev-bin:
  issuer-api-dev-obj:
  immunization-api-dev-bin:
  immunization-api-dev-obj:
  frontend-npm-cache:
